### ISSUE TITLE
iOS 13 support

### ISSUE THREAD

**Issue by SarKaa** [cosmosgenius/screendump#10]
This tweak is one I would kill for, and so would a lot of others in the JB community, but it isn't compatible, waiting on the Dev to improve in his amazing work,

**Comment by rullinoiz** [comment]
agreed, this is amazing but its a shame it doesn't support ios 13

**Comment by SarKaa** [comment]
This has been updated by juilioverne to work with ios 13

**Comment by rndwalker** [comment]
If someone happens to see this, juilioverne's fork also works with Meridian, tested on iOS 10.1.1 (＃°Д°)

**Comment by rullinoiz** [comment]
> This has been updated by juilioverne to work with ios 13

can you please tell me where it is? i really want this

**Comment by SarKaa** [comment]
> > This has been updated by juilioverne to work with ios 13
> 
> can you please tell me where it is? i really want this

It’s on his repo : http://julioverne.github.io/

**Comment by danieltroger** [comment]
https://github.com/julioverne/screendump is his screendump fork to be exact
