### ISSUE TITLE
Autoload screendump when jailbreaked + Workaround

### ISSUE THREAD

**Issue by bigrck64** [cosmosgenius/screendump#3]
Everytime I reboot my phone, I launch the jailbreak process with unc0ver, but screendump is not starting. (ios 11, unc0ver 3)

Here is the workaround we coded, feel free to improve it Sharat :)

---

The problem is that “screen” is null when the VNCUpdateRunState() is called, so the server can not start on jailbreak respring.

So we removed the call from loadPrefs (too soon) :
![Autostart1](https://user-images.githubusercontent.com/9383270/74665515-32602380-51a0-11ea-8fc5-141994386a7c.png)

And we add it inside OnFrameUpdate:
![Autostart2](https://user-images.githubusercontent.com/9383270/74665525-38ee9b00-51a0-11ea-9d32-1a6f393b8cf9.png)

**Comment by cosmosgenius** [comment]
So this is a correct fix + the handling of the notification from preferenceloader. I have fixed in #7

**Comment by bigrck64** [comment]
Thanks for update, it's nice to see you active 👍
