### ISSUE TITLE
Add VNCPassword feature + Example

### ISSUE THREAD

**Issue by bigrck64** [cosmosgenius/screendump#4]
Hello Sharat

Veency had a nice feature you drop: the password authentification.
Finally it would be very simple to add it back, I suggest you to add a new preference to be able to change it on the phone, then use the Saurik code to match the password if not null :)

---

Demo with password in hard set to "screendump"
![PasswordCheck](https://user-images.githubusercontent.com/9383270/74666380-acdd7300-51a1-11ea-8825-5498f8ae920a.png)

**Comment by cosmosgenius** [comment]
Added password in #8

**Comment by bigrck64** [comment]
Nice ! :-)
